name: ci

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.f.outputs.changes }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: dorny/paths-filter@v4
        id: f
        with:
          filters: |
            counters: counters/**
            messagepipeline: messagepipeline/**
            muxsub: muxsub/**
            fastingest: fastingest/**

  test:
    needs: detect
    if: needs.detect.outputs.modules != '[]'
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.detect.outputs.modules) }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.7.x

      - name: install nats-server
        if: matrix.module == 'fastingest'
        uses: aricart/install-binary@v2.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server

      - name: lint
        working-directory: ${{ matrix.module }}
        run: deno fmt --check --ignore=docs/

      - name: test
        working-directory: ${{ matrix.module }}
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: deno test --allow-all --unstable --parallel --fail-fast --coverage=./cov
