name: messagepipelines

on:
  push:
    paths:
      - 'messagepipeline/**'
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    paths:
      - 'messagepipeline/**'
    branches: [main]

jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      matrix:
        deno-version: [1.42.4]

    steps:
      - name: Git Checkout messagepipelines
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Lint Deno Module
        run: |
          cd messagepipeline
          deno fmt --check --ignore=docs/
        

      - name: Test Deno Module
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: |
          cd messagepipeline
          deno test --allow-all --unstable --parallel --fail-fast --coverage=./cov 

