name: muxsub npm release

on:
  release:
    types: [created]
    tags:
      - "muxsub/*"

jobs:
  test:
    environment: CI
    strategy:
      matrix:
        deno-version: [2.5.x]
        node-version: [24.x]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Test
        working-directory: muxsub
        run: |
          npm install
          npm run build
      - name: Publish
        run: |
          cd muxsub
          npm publish --provenance --access public --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
