name: nhgc release

on:
  push:
    tags:
      - 'nhgc/*'

jobs:
  test:
    environment: CI
    strategy:
      matrix:
        deno-version: [1.42.4]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Git Checkout NHGC
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        working-directory: nhgc
        run: deno bundle nhgc/mod.ts nhgc/mod.mjs

      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: mod.mjs
          repo-token: ${{ secrets.GH_TOKEN }}
