name: nhgc release

on:
  release:
    types: [created]
    tags:
      - 'nhgc/*'

jobs:
  test:
    strategy:
      matrix:
        deno-version: [1.41.3]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Git Checkout NHGC
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: deno bundle nhgc/mod.ts nhgc/mod.mjs
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          path: nhgc/mod.mjs
