name: NATS.deno

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      matrix:
        deno-version: [1.42.1]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Set NATS Server Version
        run: echo "NATS_VERSION=v2.10.12" >> $GITHUB_ENV

      # this here because dns seems to be wedged on gha
#      - name: Add hosts to /etc/hosts
#        run: |
#          sudo echo "145.40.102.131 demo.nats.io" | sudo tee -a /etc/hosts

      - name: Get nats-server
        run: |
          wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
          unzip tmp.zip
          mv nats-server-$NATS_VERSION-linux-amd64 nats-server
          rm nats-server/README.md LICENSE

      - name: Lint Deno Module
        run: deno fmt --check --ignore=docs/

      - name: Test Deno Module
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
        run: |
          deno test --allow-all --unstable --parallel --fail-fast --coverage=./cov nhgc

